baseurl:  /
destination: ./_site

exclude: ['README.markdown']

future: true
lsi: false
markdown: rdiscount
highligher: pygments
permalink: /logs/:title/
paginate: 5

rdiscount:
  extensions: [smart]
