title: Rohit Yadav
author: Rohit Yadav
email: rohit@yadav.cloud
description: >
  Blog posts and talks by Rohit Yadav.

baseurl: ""
url: https://rhtyd.in
enforce_ssl: rhtyd.in

timezone: Asia/Kolkata
encoding: "utf-8"
exclude: ['README.markdown']

permalink: logs/:title/

collections:
  algorithms:
    output: true
    permalink: /algorithms/:path

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
