title: रोहित यादव
author: Rohit Yadav
email: rohit@scaleninja.com
description: >
  Writings, essays, blog posts and talks by Rohit Yadav.
baseurl: ""
url: http://rohit.yadav.xyz

markdown: kramdown
timezone: Asia/Kolkata
encoding: "utf-8"
future: true
lsi: false
exclude: ['README.markdown']
highlighter: rouge
permalink: logs/:title/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
