title: Bhaisaab
author: Rohit Yadav
email: rohit@scaleninja.com
description: >
  Writings, essays, blog posts and talks by Rohit Yadav.
baseurl: ""
url: http://bhaisaab.org

markdown: kramdown
timezone: Asia/Kolkata
encoding: "utf-8"
future: true
lsi: false
exclude: ['README.markdown']
highlighter: pygments
permalink: logs/:title/
gems:
  - jekyll-redirect-from