title: रohit Yadav
author: Rohit Yadav
email: rohit@scaleninja.com
description: >
  Blog posts and talks by Rohit Yadav.
baseurl: ""
url: https://rhtyd.in
enforce_ssl: rhtyd.in

markdown: kramdown
timezone: Asia/Kolkata
encoding: "utf-8"
future: true
lsi: false
exclude: ['README.markdown']
highlighter: rouge
permalink: logs/:title/

collections:
  algorithms:
    output: true
    permalink: /algorithms/:path

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
